services:
  app:
    container_name: app
    build:
      context: .
      args:
        - USER=$USER
    volumes:
      - .:/app
      - /app/node_modules # not used
    command: ["yarn", "dev"]
    ports:
      - 8080:3000
